// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://egjejeujcjkwgyzuebfa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVnamVqZXVqY2prd2d5enVlYmZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0NzgwOTEsImV4cCI6MjA3MjA1NDA5MX0.GdRP5igHVVQjskth0_qGgYugCgr3IkX5D4lu2xX-snk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});